### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by calamaro** [colatusso/StoreTemplate#1]
I'm getting this error trying to compile your project on Xcode 6.4 and 7.1b:

error: could not read data from '/Downloads/StoreTemplate-master/Template 1Tests/iOSAppTemplateTests-Info.plist': The file “iOSAppTemplateTests-Info.plist” couldn’t be opened because there is no such file.

**Comment by colatusso** [comment]
Hi, I pushed an update with the correction.
